resources:
  jobs:
    cf_mom_factory_job:
      name: cf-mom-factory-job-${bundle.target}
      trigger:
        file_arrival:
          url: s3://cf-mom-factory-bucket-dev/mom_factory_dev/raw/
      tasks:
        - task_key: cf_mom_factory_pipeline
          pipeline_task:
            pipeline_id: ${resources.pipelines.cf_mom_factory_pipeline.id}
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            environment_version: "5"
      permissions:
        - group_name: users
          level: CAN_VIEW
    cf_mom_factory_check_file_arrival_job:
      name: cf-mom-factory-check-file-arrival-job-${bundle.target}
      schedule:
        quartz_cron_expression: "0 0 9 * * ?"
        timezone_id: "Asia/Tokyo"
        pause_status: "PAUSED"
      tasks:
        - task_key: check_file_arrival
          spark_python_task:
            python_file: ${workspace.file_path}/src/02_mom_factory/jobs/check_file_arrival.py
            parameters:
              - ${var.mom_catalog_name}
          disable_auto_optimization: true
          max_retries: 0
          email_notifications:
            on_failure:
              - matsuot@revolvesys.co.jp
              - kawanishiy@revolvesys.co.jp
          environment_key: Default
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            environment_version: "5"